config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api do
    namespace :v1 do
      post 'sessions' => 'sessions#create'
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  
  devise_for :users, controllers: { passwords: 'devise/passwords' }
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :likes, foreign_key: :author_id
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true, allow_blank: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  before_create :set_initial_posts_counter
  before_save :generate_api_token

  def update_posts_counter
    update_column(:posts_counter, posts.count)
  end

  def update_comments_counter
    update_column(:comments_counter, comments.count)
  end

  def last_posts
    posts.order(created_at: :desc).limit(3)
  end

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= 'user'
  end

  private

  def generate_api_token
    self.api_token = SecureRandom.hex(16)
  end

  def set_initial_posts_counter
    self.posts_counter = 0
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id]) || not_found
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<main>
  <section>
    <ul class="card-container">
      <% @users.each do |user| %>
        <%= link_to user_path(user) do %>
          <li class="card">
            <div class="flex">
              <div class="photo-container">
                <% if user.photo.present? %>
                  <%= image_tag(user.photo, class: "user-img") %>
                <% else %>

                <% end %>
              </div>
              <div class="user-information flex">
                <h2><%= user.name %></h2>
                <p>Number of posts: <%= user.posts_counter %></p>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </section>
</main>

app/views/users/show.html.erb
<main>
  <section class="card-container">
    <div class="card flex"> 
      <div class="photo-container">
        <% if @user.photo.present? %>
          <%= image_tag(@user.photo, class: "user-img") %>
        <% else %>
        
        <% end %>
      </div>
      <div class="user-information flex">
        <h1><%= @user.name %></h1>
        <p>Number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
  </section>

  <%# Bio Section %>
  <section class="user-information bio">
    <h2>Bio</h2>
    <p><%= @user.bio %></p>
  </section>

  <%# Posts Section %>
  <section>
    <ul class="card-container">
      <% @user.last_posts.each do |post| %>
        <%= link_to user_posts_path(@user) do %>
          <li class="card">
            <h3 class="title"><%= post.title%></h3>
            <h4 class="text"><%= post.text%></h4>
            <div class="flex counters">
              <p>Comments: <%= post.comments_counter %> | Likes: <%= post.likes_counter %></p>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <div class="btn-container"> 
      <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "btn" %>
    </div>
  </section> 
</main>






