config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api do
    namespace :v1 do
      post 'sessions' => 'sessions#create'
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  
  devise_for :users, controllers: { passwords: 'devise/passwords' }
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  after_create :update_user_posts_counter
  after_create :update_comments_counter
  after_create :update_likes_counter

  validates :comments_counter, numericality: { only_integer: true, allow_nil: true },
                               comparison: { greater_than_or_equal_to: 0, allow_nil: true }
  validates :likes_counter, numericality: { only_integer: true, allow_nil: true },
                            comparison: { greater_than_or_equal_to: 0, allow_nil: true }
  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }

  def update_user_posts_counter
    author.update_posts_counter
  end

  def update_comments_counter
    update(comments_counter: comments.count)
  end

  def update_likes_counter
    update(likes_counter: likes.count)
  end

  def last_comments
    comments.order(created_at: :desc).includes([:author]).limit(5)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    posts = User.find(params['user_id']).posts

    render json: posts
  rescue StandardError
    render json: { error: 'User not found' }, status: :bad_request
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments, :likes).paginate(page: params[:page], per_page: 2)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_path(id: @post.author_id), notice: 'Post was successfully created.'
    else
      flash.now[:alert] = 'An error has occurred while creating the post.'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @author = @post.author
    @author.decrement!(:posts_counter)
    @post.destroy!
    redirect_to user_posts_path(id: @author.id), notice: 'Post deleted!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<main>
  <section class="card-container">
    <div class="card flex"> 
      <div class="photo-container">
        <% if @user.photo.present? %>
          <%= image_tag(@user.photo, class: "user-img") %>
        <% else %>
        <% end %>
      </div>
      <div class="user-information flex">
        <h1><%= @user.name %></h1>
        <p>Number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
  </section>

  <%# Posts Section %>
  <section>
    <div class="btn-container">
     <% if current_user %>
        <%= link_to "Create a post",new_user_post_path(@user), class: "btn" %>
      <% end %>
    </div>

    <ul>
      <% @posts.each do |post| %>
        <%= link_to user_post_path(user_id: post.author_id, id: post.id) do %>
          <li class="post-box">
            <div class="content-box"> 
              <h2 class="title"><%= post.title%></h2>
              <h4 class="text"><%= post.text%></h4>
              <div class="flex counters">
                <p>Comments: <%= post.comments_counter %> | Likes: <%= post.likes_counter %></p>
              </div>
            </div>
            <%# Comments Section %>
            <div class="content-box">
              <h2>Comments:</h2>
              <ul>
                <li>
                  <% post.last_comments.each do |comment| %>
                    <p class="text"> <%= comment.author.name %>: <%= comment.text %> </p>
                  <% end %>
                </li>
              <ul>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <div class="pagination-container">
      <%= will_paginate @posts, inner_window: 1, outer_window: 0, previous_label: 'Pagination', next_label: 'Pagination' %>
    </div>
  </section> 
</main>

app/views/posts/new.html.erb
<main>
  <h1 class="title"> Create a new Post! </h1>
  <%= form_with model: @post, url: user_posts_path, class: "form-container" do |form| %>
    <%= form.label :title, class: "form-title" %>
    <%= form.text_field :title, class:"input" %>
    <%= form.label :text, class: "form-title" %>
    <%= form.text_area :text , cols: 40, rows: 20, class:"input" %>
    <%= form.submit "Submit", class: "btn form-btn" %>
  <% end %>
</main>

app/views/posts/show.html.erb
<main>
  <section class="post-box">
    <div class="content-box"> 
      <div class="flex post-header"> 
        <h3 class="title"> <%= @post.title %> by <%= @post.author.name %> </h3>
        <h4 class="counters"> Comments: <%= @post.comments_counter %> | Likes: <%= @post.likes_counter %></h4>
      </div>
      <p class="text"><%= @post.text %></p>
    </div>

    <%# Comments Section %>
    <div>
      <h3 class="subtitle">Comments:</h3>
      <ul>
        <% @post.comments.includes(:author).includes(:post).each do |comment| %>
          <div class="flex comment-container">
            <p class="text"><%= comment.author.name %>: <%= comment.text %></p>
            <% if can? :destroy, comment %>
              <%= button_to "Delete Comment", user_post_comment_path(user_id: comment.author.id, post_id: comment.post.id, id: comment.id), method: :delete, class: "btn mini-btn"  %>
            <% end %>
          </div>
        <% end %>
      </ul>
      <div class="flex post-btn">
        <% if user_signed_in? %>
          <%= link_to "New Comment", new_user_post_comment_path(user_id: @post.author_id, post_id: @post.id ), class: "btn" %>
          <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |form| %>
            <%= form.submit "Like the post", class: "btn" %>
          <% end %>
          <% if can? :destroy, @post %>
            <%= button_to "Delete post", user_post_path(user_id: @post.author.id, post_id: @post.id), method: :delete, class: "btn delete-btn"  %>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
</main>